Sqlite:
  path: '...'
Whitelist:
  CheckUUID: true
  CheckName: false
  KickMessageUUID: "You are not registered to MCStuco. Please visit our official website: https://www.mcstuco.net"
  KickMessageName: "You are not registered to MCStuco. Please visit our official website: https://www.mcstuco.net"
